version: "3.9"
services:
  #postgres DB for Spring
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:latest
    container_name: 'rabbitmq'
    ports:
      - "5673:5672"
      - "15673:15672"
      - "61614:61613"
    volumes:
      - ./rabbitmq/etc/:/etc/rabbitmq/
      - ./rabbitmq/mnesia/:/var/lib/rabbitmq/mnesia
      - ./rabbitmq/logs/:/var/log/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    command: >
      /bin/sh -c "rabbitmq-plugins enable rabbitmq_stomp;
      rabbitmq-server"

#Docker volumes for persistent storage
volumes:
  postgres:
